import type { SopContent } from '@sop/shared';

type TextItem = { text: string };

/**
 * Render an SOP to an HTML document suitable for export.
 * Includes watermark option for free plan exports.
 */
export function renderSopToHtml(
  content: SopContent,
  options: {
    title: string;
    version: string;
    author: string;
    createdAt: string;
    watermark: boolean;
  },
): string {
  const watermarkCss = options.watermark
    ? `
    .watermark {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-45deg);
      font-size: 80px;
      color: rgba(200, 200, 200, 0.3);
      pointer-events: none;
      z-index: 1000;
      white-space: nowrap;
    }`
    : '';

  const watermarkHtml = options.watermark
    ? '<div class="watermark">SOP Builder — Free Plan</div>'
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(options.title)} — ${escapeHtml(options.version)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 8px; color: #0a0a0a; }
    h2 { font-size: 18px; margin-top: 24px; margin-bottom: 8px; color: #333; border-bottom: 1px solid #e0e0e0; padding-bottom: 4px; }
    p { margin-bottom: 12px; }
    ol, ul { margin-left: 24px; margin-bottom: 12px; }
    li { margin-bottom: 4px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
    .checklist li { list-style: none; margin-left: 0; }
    .checklist li::before { content: "☐ "; }
    @media print { body { padding: 20px; } }
    ${watermarkCss}
  </style>
</head>
<body>
  ${watermarkHtml}
  <h1>${escapeHtml(options.title)}</h1>
  <p class="meta">Version ${escapeHtml(options.version)} • Author: ${escapeHtml(options.author)} • ${escapeHtml(options.createdAt)}</p>

  <h2>Purpose</h2>
  <p>${escapeHtml(content.purpose)}</p>

  <h2>Scope</h2>
  <p>${escapeHtml(content.scope)}</p>

  <h2>Roles & Responsibilities</h2>
  <p>${escapeHtml(content.roles)}</p>

  ${content.preconditions ? `<h2>Preconditions</h2><p>${escapeHtml(content.preconditions)}</p>` : ''}
  ${content.tools ? `<h2>Tools & Materials</h2><p>${escapeHtml(content.tools)}</p>` : ''}

  <h2>Step-by-Step Procedure</h2>
  <ol>
    ${content.steps.map((s: TextItem) => `<li>${escapeHtml(s.text)}</li>`).join('\n    ')}
  </ol>

  <h2>Checklist</h2>
  <ul class="checklist">
    ${content.checklistItems.map((c: TextItem) => `<li>${escapeHtml(c.text)}</li>`).join('\n    ')}
  </ul>

  ${
    content.exceptions.length > 0
      ? `<h2>Exceptions & Edge Cases</h2><ul>${content.exceptions.map((e: TextItem) => `<li>${escapeHtml(e.text)}</li>`).join('\n    ')}</ul>`
      : ''
  }

  ${content.kpis ? `<h2>KPIs & Quality Checks</h2><p>${escapeHtml(content.kpis)}</p>` : ''}
  ${content.risks ? `<h2>Risks & Mitigations</h2><p>${escapeHtml(content.risks)}</p>` : ''}
  ${content.references ? `<h2>References</h2><p>${escapeHtml(content.references)}</p>` : ''}

  <hr style="margin-top: 40px; border: none; border-top: 1px solid #e0e0e0;">
  <p class="meta" style="margin-top: 12px;">Generated by SOP Builder</p>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
